### ISSUE TITLE
커리어, 로그인페이지 등에 배경이미지가 안 들어감.

### ISSUE THREAD

**Issue by JerryKim1023** [KEEMSY/F5_TEAM3#28]
1. 이미 짜여진 칸이 있는데 그 칸에 맞춰서 넣으려고 했는데 이미지가 원하는 프레임 모양대로 안 들어감
2. custom.js에 data-bg-img 에 url 넣어서 css 먹여주는 부분이 있는데 원하는대로 잘 안나옴.
3. 그래서 우선은 우리 필요한 구성 ui틀을 먼저 만들고 세세한 이쁜 모양새는 나중에 하는 게 좋아보임.

**Comment by KEEMSY** [comment]
해결경로 수정을
